### ISSUE TITLE
Add 'rerun' to cb_types

### ISSUE THREAD

**Issue by bhashagemini** [akavbathen/pytest_html_merger#1]
Can you add this to cb_types to support rerun count
"rerun": [0, ""]

![image](https://user-images.githubusercontent.com/96084324/162273770-97500ab7-6950-42d3-b4b5-76d8f8746e8a.png)
![image](https://user-images.githubusercontent.com/96084324/162273886-15b0e4c1-39f6-46a9-a89a-50f29ab88622.png)

**Comment by bhashagemini** [comment]
@akavbathen

**Comment by progovoy** [comment]
Added in 0.0.9 for pytest-html 4
